---
- name: install required python modules (pre-install)
  pip: name={{ item }} extra_args="--upgrade" executable=pip3
  with_items:
  - colorlog
  - sqlalchemy

- name: create directories
  file: path={{ ha_conf_dir }} state=directory mode=02775 owner={{ palace_user }} group={{ palace_user }}

- name: install latest version of Home Assistant
  pip: name=homeassistant extra_args="--upgrade" executable=pip3

- name: copy configuration files
  template:
    src: "{{ item }}"
    dest: "{{ ha_conf_dir }}"
    owner: "{{ palace_user }}"
    group: "{{ palace_user }}"
    mode: 0644
  with_items:
    - configuration.yaml
    - fitbit.conf
    - known_devices.yaml
  notify: Restart HA
