---
- name: install commonly-named packages
  package: name={{ item }} state=present
  with_items:
  - python3
  - python3-pip
  - gcc

- name: install Debian-specific packages
  package: name={{ item }} state=present
  with_items:
  - python3-dev
  when: ansible_distribution == "Debian"

- name: install Debian-required pip packages
  pip: name={{ item }} state=present executable=pip3
  with_items:
  - appdirs
  - packaging
  when: ansible_distribution == "Debian"

- name: create user
  user: name={{ palace_user }} comment="Home Assistant" createhome=no system=yes shell="/sbin/nologin"

- name: create directory
  file: path={{ ha_conf_dir }} state=directory mode=02775 owner={{ palace_user }} group={{ palace_user }}
