---
- name: install commonly-named packages
  package: name={{ item }} state=present
  with_items:
  - python3
  - python3-pip
  - gcc
  - python3-dev

- name: install required pip packages
  pip: name={{ item }} state=present executable=pip3
  with_items:
  - appdirs
  - packaging
  - firewall

- name: download libssl deb
  get_url:
    url: http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
    dest: /tmp/libssl.deb
    mode: 0440

- name: download libssl deb
  get_url:
    url: http://ftp.debian.org/debian/pool/main/libw/libwebsockets/libwebsockets3_1.2.2-1_armhf.deb
    dest: /tmp/libwebsockets.deb
    mode: 0440

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  with_items:
    - /tmp/libssl.deb
    - /tmp/libwebsockets.deb

- name: create user
  user: name={{ palace_user }} comment="Clarks Palace" createhome=no system=yes shell="/sbin/nologin"
