---
- name: Restart HA
  service:
    name: 'home-assistant'
    state: 'restarted'

- name: Restart Mosquitto
  service:
    name: 'mosquitto'
    state: 'restarted'

- name: Reload Mosquitto
  service:
    name: 'mosquitto'
    state: 'reloaded'
